import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import WalletConnect from '../components/WalletConnect'
import { useStoreActions, useStoreState } from "../utils/store"

import { useEffect } from 'react'
import Chat from '../components/Chat'


const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.wallet)

  /*   useEffect(() => {
      if (lucid) {
        const address = lucid.wallet.address()
          .then((address: string) => {
            console.log(address)
            const payload = utf8ToHex("Hello from Lucid!");
            lucid.newMessage(address, payload).sign()
              .then((signedMessage => {
                const hasSigned: boolean = lucid.verifyMessage(address, payload, signedMessage);
                console.log(hasSigned);
              }))
          })
      } else {
        initLucid()
      }
    }, [lucid]) */
  useEffect(() => {
    console.log(walletStore)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="navbar bg-base-100">
        <div className="flex-1">
          <a className="btn btn-ghost normal-case text-xl">Cardano</a>
        </div>
        <div className="flex-none">
          <WalletConnect />
        </div>
      </div>
        <div>{walletStore.address}</div>
        <Chat />
    </div>
  )
}

export default Home
