import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import WalletConnect from '../components/WalletConnect'
import { useStoreActions, useStoreState } from "../utils/store"

import { useEffect } from 'react'
import Chat from '../components/Chat'
import Link from 'next/link'


const Home: NextPage = () => {
  const walletStore = useStoreState((state: any) => state.wallet)

  useEffect(() => {
    console.log(walletStore)
  }, [])

  return (
    <div className="px-10">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="navbar bg-base-100">
        <div className="flex-1">
          <Link href="/" className="btn btn-ghost normal-case text-xl">Cardano</Link>
        </div>
        <div className="flex-none">
          <WalletConnect />
        </div>
      </div>
        <Chat />
    </div>
  )
}

export default Home
